# Copyright (c) 2020-2021-2022-2023 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
#
# The peculiarity of this workflow is that assumes vcpkg is NOT stored as a submodule of 
# this repository.
# The workflow does the following:
# - Using the provided Git commit id, sets up vcpkg if needed, then run CMake with
#   CMakePreset.json using a configuration that leverages the vcpkg's toolchain file. 
#   This will automatically run vcpkg to install dependencies described by the vcpkg.json
#   manifest file. 
#   vcpkg's Binary Caching backed by GH Action cache is being used. It will be a no-op if 
#   the dependencies are restored from GH Action cache.
# - Finally builds the sources with Ninja.
name: hosted-ninja-vcpkg-cacheoff
on: [push, workflow_dispatch]

jobs:
  job:
    name: Zamboni-good
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Dump the content of $RUNNER_TEMP
        run: find $RUNNER_TEMP
        shell: bash
      - name: Dump the content of $RUNNER_WORKSPACE
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          # This specifies the location of vcpkg, where it is going to be restored from cache, or create from scratch.
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          # The vcpkg.json file, which will be part of cache key computation.
          vcpkgJsonGlob: '**/vcpkg.json'
          vcpkgGitCommitId: 4bb07a326d9b9bce3703272a509e5bc25dd9cfd5

      - name: Prints output of run-vcpkg's action
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}'"

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'
          cmakeListsTxtPath: '${{ github.workspace }}/lukka-test/CMakeLists.txt'
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg
