name: kosak-build
run-name: Probably can't bootstrap now?
on: [push, workflow_dispatch]

jobs:
  job:
    name: Build prog1
    runs-on: windows-2025

    steps:
      # Check out my repo
      - uses: actions/checkout@v5

      # Check out vcpkg
      - uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg

      # Install vcpkg
      - shell: cmd
        run: vcpkg/bootstrap-vcpkg.bat

      # Run cmake
      - shell: cmd
        run: cmake -S cpp/prog1 -B cpp/prog1/build --toolchain ${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
