name: kosak-build
run-name: maybe it actually builds
on: [push, workflow_dispatch]

jobs:
  job:
    name: Build prog1
    runs-on: windows-2025

    steps:
      # echo sad
      - run: echo ${{ github.workspace }}
      - run: echo ${{ runner.workspace }}

      # Check out my repo
      - uses: actions/checkout@v5

      # Check out vcpkg
      - uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      # Install vcpkg
      - shell: cmd
        run: ./vcpkg/bootstrap-vcpkg.bat

      # Run cmake configuration
      - shell: cmd
        run: cmake -S cpp/prog1 -B cpp/prog1/build --toolchain ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      # Run cmake build
      - shell: cmd
        run: cmake --build cpp/prog1/build --config RelWithDebInfo
